version: '3.7'

networks:
  elastic-net:
    driver: bridge

services:
  setup:
    image: elasticsearch:8.15.0
    networks:
      - elastic-net
    command: >
      bash -c '
        echo "Setting kibana_system password";
        until curl -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: [ "CMD-SHELL", "true" ]
      interval: 1s
      timeout: 5s
      retries: 120

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: elasticsearch
    depends_on:
      setup:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:9200 | grep -q 'missing authentication credentials'" ]
      interval: 30s
      timeout: 10s
      retries: 120

  kibana:
    image: kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - xpack.security.enabled=false
    env_file:
      - .env
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic-net

volumes:
  esdata:
    driver: local
